language: c
os:
  - linux
dist: focal
arch:
  - amd64
before_install:
  - sudo apt-get update -y
install:
  - sudo apt-get install -y gcovr
script:
  - cmake -B ./build
  - cmake --build ./build
  - cd ./build && make test codecov && echo "$CODECOV_TOKEN" > .cct && bash <(curl -s https://codecov.io/bash) -f ./codecov.xml -t @./.cct
