language: c
os:
  - linux
dist: focal
arch:
  - amd64
before_install:
  - sudo apt-get update -y
install:
  - sudo apt-get install -y gcovr
script:
  - cmake -B ./build
  - cmake --build ./build
  - make -C ./build test codecov && echo "$CODECOV_TOKEN" > ./build/cct && bash <(curl -s https://codecov.io/bash) -f ./build/codecov.xml -t @./build/cct

