language: c
os:
  - linux
dist: focal
arch:
  - amd64
before_install:
  - sudo apt-get update -y
install:
  - sudo apt-get install -y libcmocka-dev
script:
  - cmake -B ./build
  - cmake --build ./build
  - ./build/src/container/list_singly_linked_test