codecov:
  token: "95c7bd2c-2e83-4a77-8256-505de1f77a02"
  bot: "codecov-io"
  ci:
    - "travis.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
