name: Main
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: sudo apt-get update -y && sudo apt-get install -y cmake libcmocka-dev && cd ..
      - name: CMake and Build
        run: cmake -B ./build && cmake --build ./build
      - name: Run test
        run: ./build/src/container/list_singly_linked_test
