name: Main
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Ready
        run: sudo apt-get update -y && sudo apt-get install -y cmake libcmocka-dev
      - name: CMake and Build
        run: cmake -B ./build && cmake --build ./build
      - name: Run
        run: ./build/src/container/list_singly_linked_test
